# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Deployment',
                'verbose_name_plural': 'Deployments',
            },
        ),
        migrations.CreateModel(
            name='templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flavor', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.AddField(
            model_name='deployment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template_app.templates'),
        ),
    ]
